services:
  ventafacil.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Ventafacil123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ventafacil.pfx
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro